image: docker:stable

# Comentario
stages:
 - teste
 - package
 - build
 - deploy-dsv 
 - deploy-hmg

teste:
  image: maven:3.6.0-jdk-11
  stage: teste
  tags:
  - disteds 
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^desenvolvimento/'
  script:
    - mvn clean --settings .mvn/custom-settings.xml org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report
    - mvn verify --settings .mvn/custom-settings.xml sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.coverage.jacoco.xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ',')
    - cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    when: always
    reports:
      junit:
        - "target/surefire-reports/TEST-*.xml"
        - "target/failsafe-reports/TEST-*.xml"


package-jar:
  image: maven:3.6.0-jdk-11
  stage: package
  tags:
  - disteds 
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME !~ /^desenvolvimento/'
  script:
    - mvn package -Dmaven.test.skip --settings .mvn/custom-settings.xml 
    - echo "VERSION=$(mvn --settings .mvn/custom-settings.xml --non-recursive help:evaluate -Dexpression=project.version | grep -v '\[.*')" >> package.env
  artifacts:
    when: always
    paths:
      - target/*.jar
    expire_in: 2 day
    reports:
      dotenv: package.env


build-docker: 
  stage: build
  tags:
  - disteds
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^feature-fontes/'
  dependencies:
  - package-jar
  services:
  - docker:19-dind
  retry: 2 
  before_script:
  - docker info
  - docker login harbor.fazenda.mg.gov.br -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
  - docker build -t harbor.fazenda.mg.gov.br/disteds_itcd/controle-pagamento:$VERSION .
  - docker push harbor.fazenda.mg.gov.br/disteds_itcd/controle-pagamento:$VERSION


deploy-project-dsv:
  stage: deploy-dsv
  tags:
  - disteds 
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^feature-fontes/'
  dependencies:
  - package-jar
  - build-docker
  before_script:
    #- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client tar -y )' # Somente se não possuir ssh-agent no container
    - eval $(ssh-agent -s)
    - printenv "SW_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa 172.23.201.52 >> ~/.ssh/known_hosts
  script:
  - docker login harbor.fazenda.mg.gov.br -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  - export DOCKER_HOST=ssh://gitlab-runner@172.23.201.52
  - docker stack deploy -c docker-compose.yml controle-pagamento --with-registry-auth
  - docker service logs controle-pagamento_itcd-cm
  
deploy-project-hmg:
  stage: deploy-hmg
  tags:
  - disteds 
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^stable/'
  dependencies:
  - package-jar
  - build-docker
  before_script:
    #- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client tar -y )' # Somente se não possuir ssh-agent no container
    - eval $(ssh-agent -s)
    - printenv "SW_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa 172.23.201.52 >> ~/.ssh/known_hosts
  script:
  - docker login harbor.fazenda.mg.gov.br -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  - export DOCKER_HOST=ssh://gitlab-runner@172.23.201.52
  - docker stack deploy -c docker-compose-hmg.yml controle-pagamento-hmg --with-registry-auth
  #- docker service logs itcd-cm_itcd-cm
  
  
